# -*- coding: utf-8 -*-
"""practica.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XF8SJMi8KuJ3hxTZOMGE0hOMfsJ2SsZm
"""

#autor:     Ricardo Rivera

import math

def calcular_distancia(x1, y1, x2, y2):
    distancia = math.sqrt((x2 - x1)**2 + (y2 - y1)**2)
    return distancia

# Solicitar al usuario las coordenadas de los dos puntos
x1 = float(input("Ingrese la coordenada x del primer punto: "))
y1 = float(input("Ingrese la coordenada y del primer punto: "))
x2 = float(input("Ingrese la coordenada x del segundo punto: "))
y2 = float(input("Ingrese la coordenada y del segundo punto: "))

# Calcular la distancia usando la función calcular_distancia
distancia = calcular_distancia(x1, y1, x2, y2)

# Mostrar el resultado
print(f"La distancia entre los dos puntos es: {distancia}")
input("presiona otra tecla para salir ")
